config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  resources :events do
    resources :volunteers
    resources :jobs
    resources :schedules
  end

  resources :assignments, only: [] do
    member do
      put :toggle_absent
      put :toggle_confirmed
    end
  end

end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
  has_and_belongs_to_many :jobs, dependent: :destroy
  belongs_to :event
  has_many :assignments

  validates :name, uniqueness: true

  def sorted_for(event)
    volunteers = where(event: event)
    volunteers.sort_by(&:sortable_name)
  end

  def sortable_name
    names = name.split(' ')
    last_name = names.pop
    sortable_names = [last_name] + names
    sortable_names.join(' ')
  end

  def display_name
    names = name.split(' ')
    last_initial = names.last[0]
    [names[0], last_initial].join(' ')
  end
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  before_action :set_volunteer, only: [:show, :edit, :update, :destroy]

  # GET /volunteers
  # GET /volunteers.json
  def index
    @volunteers = Volunteer.all
  end

  # GET /volunteers/1
  # GET /volunteers/1.json
  def show
  end

  # GET /volunteers/new
  def new
    @event  = Event.find(event_id)
    @jobs   = @event.jobs
    @volunteer = Volunteer.new
  end

  # GET /volunteers/1/edit
  def edit
    @event  = Event.find(event_id)
    @jobs   = @event.jobs
  end

  # POST /volunteers
  # POST /volunteers.json
  def create
    @event = Event.find(event_id)
    @volunteer = @event.volunteers.build(volunteer_params)

    respond_to do |format|
      if @volunteer.save
        format.html { redirect_to event_path(@event), notice: 'Volunteer was successfully created.' }
        format.json { render :show, status: :created, location: @volunteer }
      else
        format.html { render :new }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /volunteers/1
  # PATCH/PUT /volunteers/1.json
  def update
    @event = Event.find(event_id)
    respond_to do |format|
      if @volunteer.update(volunteer_params)
        format.html { redirect_to event_path(@event), notice: 'Volunteer was successfully updated.' }
        format.json { render :show, status: :ok, location: @volunteer }
      else
        @jobs = @event.jobs
        format.html { render :edit }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /volunteers/1
  # DELETE /volunteers/1.json
  def destroy
    @event  = Event.find(event_id)
    @volunteer.destroy
    respond_to do |format|
      format.html { redirect_to event_url(@event), notice: 'Volunteer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_volunteer
      @volunteer = Volunteer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def volunteer_params
      params.require(:volunteer).permit(:name, :event_id, job_ids: [])
    end

    def event_id
      params.require(:event_id)
    end
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/volunteers/_form.html.erb
<%= simple_form_for([@event, @volunteer]) do |f| %>
  <% if @volunteer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@volunteer.errors.count, "error") %> prohibited this volunteer from being saved:</h2>

      <ul>
      <% @volunteer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name, autofocus: true %>
  <%= f.association :jobs, collection: @jobs %>
  <%= f.button :submit, class: 'button' %>
<% end %>

app/views/volunteers/edit.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'Events', events_path %></li>
  <li><%= link_to @event.name, event_path(@event) %></li>
  <li>Editing <%= @volunteer.name %></li>
<% end %>

<div class="row">
  <div class="small-6 small-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/volunteers/index.html.erb
<h1>Listing volunteers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @volunteers.each do |volunteer| %>
      <tr>
        <td><%= volunteer.name %></td>
        <td><%= volunteer.event %></td>
        <td><%= link_to 'Show', volunteer %></td>
        <td><%= link_to 'Edit', edit_volunteer_path(volunteer) %></td>
        <td><%= link_to 'Destroy', volunteer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Volunteer', new_volunteer_path %>

app/views/volunteers/new.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'Events', events_path %></li>
  <li><%= link_to @event.name, event_path(@event) %></li>
  <li>New Volunteer</li>
<% end %>

<%= render 'form' %>

<%= link_to 'Cancel', event_path(@event), class: 'button alert tiny' %>