config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  resources :events do
    resources :volunteers
    resources :jobs
    resources :schedules
  end

  resources :assignments, only: [] do
    member do
      put :toggle_absent
      put :toggle_confirmed
    end
  end

end

app/models/job.rb
class Job < ActiveRecord::Base
  has_and_belongs_to_many :volunteers, dependent: :destroy
  belongs_to :event
  has_many :assignments
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @event  = Event.find(event_id)
    @job    = Job.new
  end

  # GET /jobs/1/edit
  def edit
    @event  = Event.find(event_id)
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @event  = Event.find(event_id)
    @job    = @event.jobs.build(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to event_path(@event), notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @event  = Event.find(event_id)
    @job.destroy
    respond_to do |format|
      format.html { redirect_to event_url(@event), notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name, :event_id)
    end

    def event_id
      params.require(:event_id)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= simple_form_for([@event, @job]) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name, autofocus: true %>
  <%= f.button :submit, class: 'button' %>
<% end %>

app/views/jobs/edit.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'Events', events_path %></li>
  <li><%= link_to @event.name, event_path(@event) %></li>
  <li>Editing <%= @job.name %></li>
<% end %>

<div class="row">
  <div class="small-6 small-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/jobs/new.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'Events', events_path %></li>
  <li><%= link_to @event.name, event_path(@event) %></li>
  <li>New Job</li>
<% end %>

<%= render 'form' %>

<%= link_to 'Cancel', event_path(@event), class: 'button alert tiny' %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @job.name %>
</p>

<p>
  <strong>Event:</strong>
  <%= @job.event %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>