config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  resources :events do
    resources :volunteers
    resources :jobs
    resources :schedules
  end

  resources :assignments, only: [] do
    member do
      put :toggle_absent
      put :toggle_confirmed
    end
  end

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :event
  has_many :days, dependent: :destroy
  has_many :assignments, through: :days
  has_many :jobs, through: :event
  has_many :volunteers, through: :event

  def add_days
    dates = (start_on..end_on).select { |day| day.wday == 0 }
    dates.each do |date|
      days.create(date: date)
    end
  end

  def add_assignments
    days.each do |day|
      event.jobs.each do |job|
        job.volunteers.each do |volunteer|
          Assignment.create(day: day, job: job, volunteer: volunteer)
        end
      end
    end
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    @event = Event.includes(:jobs).find(event_id)
    table = Tablizer::Table.new(@schedule)
    @table_data = table.tablize :assignments, {col: :job, row: :day}
  end

  # GET /schedules/new
  def new
    @event = Event.find(event_id)
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
    @event = Event.find(event_id)
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @event = Event.find(event_id)
    @schedule = @event.new_schedule(schedule_params)

    respond_to do |format|
      if @schedule.valid?
        format.html { redirect_to [@event, @schedule], notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    @event = Event.find(event_id)

    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to [@event, @schedule], notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to event_path(@schedule.event), notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:name, :start_on, :end_on, :event_id)
    end

    def event_id
      params.require(:event_id)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
  def confirmed(assignments)
    assignments.select { |a| a.confirmed }
  end
end

app/views/schedules/_cell.html.erb
<% if cell.data.kind_of?(Hash) %>
  <td class="date-column schedule-cell">
    <div class="schedule-day-job">
      <%= cell.data[:day].formatted_date %>
    </div>
    <div class="schedule-day-job-selector">
      <% cell.data[:assignments].each do |assignment| %>
        <% assignment_class = assignment.absent ? 'absent ' : '' %>

        <div class="schedule-day-job-selector-assignment <%= assignment_class %>">
          <div class="schedule-day-job-confirmed-volunteer-actions">
            <%= link_to toggle_absent_assignment_path(assignment), method: :put, class: 'schedule-day-job-confirmed-volunteer-actions-absent' do %>
              <%= icon('times') %>
            <% end %>
          </div>
          <%= assignment.volunteer.name %>
        </div>
      <% end %>
    </div>
  </td>
<% else %>
  <td class='schedule-cell'>
    <div class="schedule-day-job">
      <div class="schedule-day-job-confirmed">
        <% confirmed(cell.data).each do |confirmed| %>
          <div class="schedule-day-job-confirmed-volunteer">
            <%= confirmed.volunteer.display_name %>
          </div>
        <% end %>
      </div>
      <div class="schedule-day-job-selector">
        <% cell.data.each do |assignment| %>
          <% assignment_class = assignment.confirmed ? 'confirmed ' : '' %>
          <div class="schedule-day-job-selector-assignment <%= assignment_class %>">
            <div class="schedule-day-job-confirmed-volunteer-actions">
              <%= link_to toggle_confirmed_assignment_path(assignment), method: :put, class: 'schedule-day-job-confirmed-volunteer-actions-confirm' do %>
                <%= icon('check') %>
              <% end %>
            </div>
            <%= assignment.volunteer.name %>
          </div>
        <% end %>
      </div>
    </div>
  </td>
<% end %>

app/views/schedules/_day.html.erb
<tr>
  <%= render partial: 'cell', collection: day.cells %>
</tr>

app/views/schedules/_form.html.erb
<%= simple_form_for([@event, @schedule]) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name, autofocus: true %>
  <%= f.input :start_on, order: [:month, :day, :year] %>
  <%= f.input :end_on, order: [:month, :day, :year] %>
  <%= f.button :submit, class: 'button' %>
<% end %>

app/views/schedules/_header.html.erb
<th><%= header.data.try(:name) %></th>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', [@event, @schedule] %> |
<%= link_to 'Back', event_schedule_path(@event, @schedule) %>

app/views/schedules/index.html.erb
<h1>Listing schedules</h1>

<table>
  <thead>
    <tr>
      <th>Start on</th>
      <th>End on</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.start_on %></td>
        <td><%= schedule.end_on %></td>
        <td><%= schedule.event %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'Events', events_path %></li>
  <li><%= link_to @event.name, event_path(@event) %></li>
  <li>New Schedule</li>
<% end %>

<%= render 'form' %>

<%= link_to 'Cancel', event_path(@event), class: 'button alert tiny' %>

app/views/schedules/show.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'Events', events_path %></li>
  <li><%= link_to @event.name, event_path(@event) %></li>
  <li><%= @schedule.name %></li>
<% end %>

<div class="row">
  <div class="small-12 column">
    <table class='schedule'>
      <thead>
        <tr>
          <%= render partial: 'header', collection: @table_data.header.cells %>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'day', collection: @table_data.body,
          locals: { jobs: @event.jobs } %>
      </tbody>
    </table>
  </div>
</div>