config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  resources :events do
    resources :volunteers
    resources :jobs
    resources :schedules
  end

  resources :assignments, only: [] do
    member do
      put :toggle_absent
      put :toggle_confirmed
    end
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :volunteers, dependent: :destroy do

    def alphabetically
      self.sort do |item1, item2|
        name1 = item1.sortable_name
        name2 = item2.sortable_name

        name1 <=> name2
      end
    end
  end

  has_many :jobs,       dependent: :destroy
  has_many :schedules,  dependent: :destroy

  def new_schedule(params)
    Event.transaction do
      schedule = schedules.create(params)
      schedule.add_days
      schedule.add_assignments
      schedule
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @volunteers = @event.volunteers.alphabetically
    @jobs       = @event.jobs
    @schedules  = @event.schedules
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name, autofocus: true %>
  <%= f.button :submit, class: 'button' %>
<% end %>

app/views/events/edit.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'Events', events_path %></li>
  <li><%= link_to @event.name, event_path(@event) %></li>
  <li>Editing</li>
<% end %>

<div class="row">
  <div class="small-6 small-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<% content_for :breadcrumbs do %>
  <li>Events</li>
<% end %>

<div class="row">
  <%= link_to 'New Event', new_event_path, class: 'button expand' %>
</div>

<div class="row">
  <div class="small-12">
    <ul class="small-block-grid-2 medium-block-grid-3 large-block-grid-4">
      <% @events.each do |event| %>
        <li class='event-block'>
          <h3><%= link_to event.name, event_path(event) %></h3>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/events/new.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'Events', events_path %></li>
  <li>New Event</li>
<% end %>

<%= render 'form' %>

app/views/events/show.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'Events', events_path %></li>
  <li><%= @event.name %></li>
<% end %>

<div class="small-12">
  <p id="notice"><%= notice %></p>
</div>

<div class="row">
  <div class="small-12 column column-table-listing">
    <%= link_to new_event_schedule_path(@event), class: 'button tiny' do %>
      <%= icon('plus') %>
      New Schedule
    <% end %>
    <h3>Schedules</h3>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Start on</th>
          <th>End on</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @schedules.each do |schedule| %>
          <tr>
            <td><%= link_to schedule.name, [@event, schedule] %></td>
            <td><%= schedule.start_on %></td>
            <td><%= schedule.end_on %></td>
            <td>
              <%= link_to edit_event_schedule_path(@event, schedule) do %>
                <%= icon('edit') %>
              <% end %>
            </td>
            <td>
              <%= link_to [@event, schedule], method: :delete, data: { confirm: 'Are you sure?' } do %>
                <%= icon('trash') %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="small-6 column column-table-listing">
    <%= link_to new_event_volunteer_path(@event), class: 'button tiny' do %>
      <%= icon('plus') %>
      Add Volunteer
    <% end %>
    <h3>Volunteers</h3>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @volunteers.each do |volunteer| %>
          <tr>
            <td><%= volunteer.name %></td>
            <td>
              <%= link_to edit_event_volunteer_path(@event, volunteer) do %>
                <%= icon('edit') %>
              <% end %>
            </td>
            <td>
              <%= link_to [@event, volunteer], method: :delete, data: { confirm: 'Are you sure?' } do %>
                <%= icon('trash') %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="small-6 column column-table-listing">
    <%= link_to new_event_job_path(@event), class: 'button tiny' do %>
      <%= icon('plus') %>
      Add Job
    <% end %>
    <h3>Jobs</h3>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @jobs.each do |job| %>
          <tr>
            <td><%= job.name %></td>
            <td>
              <%= link_to edit_event_job_path(@event, job) do %>
                <%= icon('edit') %>
              <% end %>
              </td>
            <td>
              <%= link_to [@event, job], method: :delete, data: { confirm: 'Are you sure?' } do %>
                <%= icon('trash') %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>


<hr>
<div class="row">
  <div class="small-6 column">
    <%= link_to "Edit #{@event.name}", edit_event_path(@event), class: 'button expand' %>
  </div>
  <div class="small-6 column">
    <%= link_to "Destroy #{@event.name}", @event, method: :delete,
            data: { confirm: 'Are you sure?' }, class: 'button alert expand' %>
  </div>
</div>